### ISSUE TITLE
回调失败

### ISSUE THREAD

**Issue by iwinux** [bearyinnovative/jenkins-bearychat-plugin#1]
[这里](https://github.com/bearyinnovative/jenkins-bearychat-plugin/blob/master/src/main/java/jenkins/plugins/bearychat/StandardBearychatService.java#L42) 请求的 HTTP URL 会遭遇一次 301 跳转，但是跳转之后的结果是 404……所以需要改成 HTTPS 请求，或者修一下这个跳转~~

**Comment by xudifsd** [comment]
@iwinux 回调失败是什么意思？你是在用webhook么？

**Comment by iwinux** [comment]
@xudifsd 是的，这个插件必须用 webhook 吧

**Comment by xudifsd** [comment]
@iwinux 恩，301跳转是应该跳转到https，但是应该不会出现404诶。之前是好的么？有没有修改token或者inactive jenkins机器人？

**Comment by xudifsd** [comment]
fixed in https://github.com/bearyinnovative/jenkins-bearychat-plugin/pull/2

**Comment by xtang** [comment]
Fixed in #2
